[package]
name = "Todo-Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
derive_more = "2.0.1"
env_logger = "0.11.8"
log = "0.4.28"
mongodb = "3.3.0"
serde = "1.0.228"
strum = "0.27.2"
strum_macros = "0.27.2"
uuid = "1.18.1"
